- name: Install netfilter-persistent
  apt:
    name: 
      - zip
      - unzip
    state: present
- name: Download xray-core
  get_url:
    url: "https://github.com/XTLS/Xray-core/releases/download/v26.2.6/Xray-linux-64.zip"
    dest: /tmp/xray.zip
- name: Unzip xray-core
  unarchive:
    src: /tmp/xray.zip
    dest: /opt/xray-vps-setup/xray-core
    remote_src: yes
- name: Generate marzban specific values
  block:
    - name: Generate marzban user
      set_fact:
        MARZBAN_USER: "{{ lookup('password', '/dev/null length=13 chars=ascii_letters') }}"
    - name: Generate marzban password
      set_fact:
        MARZBAN_PASS: "{{ lookup('password', '/dev/null length=13 chars=ascii_letters') }}"
    - name: Generate marzban password
      set_fact:
        MARZBAN_PATH: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
    - name: Generate marzban password
      set_fact:
        MARZBAN_SUB_PATH: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
- name: Create dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/xray-vps-setup/marzban
- name: Copy config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "angie.conf.j2", dest: "/opt/xray-vps-setup/angie.conf" }
    - { src: "xray.json.j2", dest: "/opt/xray-vps-setup/marzban/xray_config.json" }
    - { src: "marzban.j2", dest: "/opt/xray-vps-setup/marzban/.env" }
    - { src: "confluence.j2", dest: "/opt/xray-vps-setup/index.html" }
    - { src: "docker_compose.yml.j2", dest: "/opt/xray-vps-setup/docker-compose.yml" }
- debug:
    msg: "Marzban password: {{ MARZBAN_PASS }}, marzban path: {{ MARZBAN_PATH }}"
