---
- name: Populate service facts
  ansible.builtin.service_facts:
- name: Get the current SSH listening port
  shell: "ss -tlnp | grep sshd | grep -Po '(?<=:)\\d+(?= )' | head -n 1"
  register: ssh_port_output
  changed_when: false
- name: Set SSH_PORT variable
  set_fact:
    SSH_PORT: "{{ ssh_port_output.stdout | default('22') | trim }}"
- name: Install docker
  include_tasks: install_docker.yml
  when: ansible_facts.services['docker'] is undefined
- name: Install/update yq
  include_tasks: install_yq.yml
- name: Generate values
  block:
    - name: Generate x25519 PIK 
      shell:
        cmd: docker run --rm ghcr.io/xtls/xray-core x25519 | head -n1 | cut -d' ' -f 2
      register: x25519_pik
    - name: Generate x25519 PBK 
      shell:
        cmd: docker run --rm ghcr.io/xtls/xray-core x25519 -i {{ x25519_pik.stdout }} | tail -2 | head -1 | cut -d' ' -f 2
      register: x25519_pbk
    - name: Generate default user
      shell:
        cmd: docker run --rm ghcr.io/xtls/xray-core uuid
      register: xray_uuid
- name: Install marzban
  include_tasks: install_marzban.yml
  when: setup_variant == "marzban"
- name: Install xray
  include_tasks: install_xray.yml
  when: setup_variant == "xray"
- name: Install warp
  include_tasks: setup_warp.yml
  when: setup_warp|default(false)|bool == true
- name: Start proxy
  community.docker.docker_compose_v2:
    project_src: /opt/xray-vps-setup
    files:
    - docker-compose.yml
- name: End xray
  include_tasks: end_xray.yml
  when: setup_variant == "xray"
